/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CompanyManager;


import business.Company.Company;
import business.Compliance.ComplianceModerator;
import business.InvestmentManager.InvestmentManager;
import business.TheBusiness.Business;
import business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author revanth
 */
public class ComplianceModeratorJPanel extends javax.swing.JPanel {

    UserAccount account;
    Business business;
    ComplianceModerator complianceModerator;
    public ComplianceModeratorJPanel(JPanel userProcessContainer, UserAccount account, Business business) {
        initComponents();
        this.business=business;
        this.account=account;
        this.complianceModerator=(ComplianceModerator)account.getUser();
        populateLiscensingTable();
        changeScreen(homepage);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listingrequests = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRegisterComp = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBtngoback = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        homepage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        allCompanies = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAllCompanies = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        managerDetails = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblInvManager = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        industryStandards = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtSmallCap = new javax.swing.JTextField();
        txtMediumCap = new javax.swing.JTextField();
        txtLargeCap = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 255));
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.CardLayout());

        listingrequests.setBackground(new java.awt.Color(255, 255, 255));
        listingrequests.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(85, 65, 118));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Approve");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        listingrequests.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, -1, 40));

        jButton2.setBackground(new java.awt.Color(85, 65, 118));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Reject");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        listingrequests.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 90, 40));

        tableRegisterComp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Company Name", "Assets", "Liabilities", "Market Cap", "Investment Manager", "Liscence Request"
            }
        ));
        jScrollPane1.setViewportView(tableRegisterComp);

        listingrequests.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 819, 120));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 65, 119));
        jLabel1.setText("Compay Manager Liscence Request");

        jBtngoback.setBackground(new java.awt.Color(85, 65, 119));
        jBtngoback.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtngoback.setForeground(new java.awt.Color(255, 255, 255));
        jBtngoback.setText("<< Back");
        jBtngoback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtngobackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jBtngoback)
                .addGap(218, 218, 218)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(457, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtngoback, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        listingrequests.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, 70));

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Company-amico.png"))); // NOI18N
        listingrequests.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 530, 450));

        add(listingrequests, "card2");

        homepage.setBackground(new java.awt.Color(255, 255, 255));
        homepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Licencing Commission");
        homepage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 90, 290, -1));

        jButton3.setBackground(new java.awt.Color(85, 65, 115));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Lisence Requests");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        homepage.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 260, 40));

        jButton4.setBackground(new java.awt.Color(85, 65, 115));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Companies and Managers Details");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        homepage.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 200, -1, 40));

        jButton6.setBackground(new java.awt.Color(85, 65, 115));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Investment Managers Details");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        homepage.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 260, 40));

        jToggleButton1.setBackground(new java.awt.Color(85, 65, 115));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Industry Standards");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        homepage.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 260, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1300, 80));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(85, 65, 119));
        jLabel3.setText("Home Page");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(496, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(330, 330, 330))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        homepage.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 60));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/college students-pana.png"))); // NOI18N
        homepage.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 530, 450));

        add(homepage, "card3");

        allCompanies.setBackground(new java.awt.Color(255, 255, 255));
        allCompanies.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblAllCompanies.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Company Name", "Capital", "Assets", "Liabilities", "Lisence Approval", "Manager", "Investment Manager"
            }
        ));
        jScrollPane2.setViewportView(tblAllCompanies);

        allCompanies.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 172, 915, 145));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1300, 80));

        jButton7.setBackground(new java.awt.Color(85, 65, 119));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("<<Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(85, 65, 119));
        jLabel10.setText("Company Details");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(337, 337, 337)
                .addComponent(jLabel10)
                .addContainerGap(514, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        allCompanies.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1190, -1));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Collab-bro.png"))); // NOI18N
        allCompanies.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 530, 450));

        add(allCompanies, "card4");

        managerDetails.setBackground(new java.awt.Color(255, 255, 255));
        managerDetails.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblInvManager.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Assigned Company"
            }
        ));
        jScrollPane3.setViewportView(tblInvManager);

        managerDetails.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(119, 142, 698, 166));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jButton5.setBackground(new java.awt.Color(85, 65, 119));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("<<Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(85, 65, 119));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Manager Details");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 552, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(387, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        managerDetails.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Profile Interface-bro.png"))); // NOI18N
        managerDetails.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, 530, 450));

        add(managerDetails, "card5");

        industryStandards.setBackground(new java.awt.Color(255, 255, 255));
        industryStandards.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Small Cap:");
        industryStandards.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 107, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Medium Cap:");
        industryStandards.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 135, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Large Cap:");
        industryStandards.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 164, -1, -1));
        industryStandards.add(txtSmallCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 100, 170, -1));
        industryStandards.add(txtMediumCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 135, 170, -1));
        industryStandards.add(txtLargeCap, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 164, 170, -1));

        jButton9.setBackground(new java.awt.Color(85, 65, 118));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("Set");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        industryStandards.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 205, 103, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setPreferredSize(new java.awt.Dimension(1350, 80));

        jButton8.setBackground(new java.awt.Color(85, 65, 119));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("<< Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(85, 65, 119));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Set Industry Standards");
        jLabel8.setPreferredSize(new java.awt.Dimension(1000, 80));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1088, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        industryStandards.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1205, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Saving money-bro.png"))); // NOI18N
        industryStandards.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 530, 450));

        add(industryStandards, "card6");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(tableRegisterComp.getSelectedRow()==-1)
        {
                JOptionPane.showMessageDialog(this, "Please select a row to process");
                return;

        }
        String selectedCompanyName=String.valueOf(tableRegisterComp.getValueAt(tableRegisterComp.getSelectedRow(), 0));
        Company selectedCompany = this.business.getCompliance().getComplianceModerator().getCompanyByName(selectedCompanyName);
        selectedCompany.setLicenseStatus("Approved");
        JOptionPane.showMessageDialog(this, "Approved!");
        populateLiscensingTable();
        changeScreen(homepage);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(tableRegisterComp.getSelectedRow()==-1)
        {
                JOptionPane.showMessageDialog(this, "Please select a row to process");
                return;

        }
        String selectedCompanyName=String.valueOf(tableRegisterComp.getValueAt(tableRegisterComp.getSelectedRow(), 0));
        Company selectedCompany = this.business.getCompliance().getComplianceModerator().getCompanyByName(selectedCompanyName);
        selectedCompany.setLicenseStatus("Rejected");
        populateLiscensingTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        changeScreen(listingrequests);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        populateAllCompaniesTable();
        changeScreen(allCompanies);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        populateInvestmentManagerTable();
        changeScreen(managerDetails);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        changeScreen(homepage);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        changeScreen(homepage);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jBtngobackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtngobackActionPerformed
        changeScreen(homepage);
    }//GEN-LAST:event_jBtngobackActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        changeScreen(homepage);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try{
            double smallCap = Double.parseDouble(txtSmallCap.getText());
            double mediumCap = Double.parseDouble(txtMediumCap.getText());
            double largeCap = Double.parseDouble(txtLargeCap.getText());
            if(smallCap>=mediumCap){
                JOptionPane.showMessageDialog(this, "Small cap cannot be larger than medium cap");
            }
            else if(mediumCap>=largeCap){
                JOptionPane.showMessageDialog(this, "Medium cap cannot be larger than large cap");
            }
            else{
                this.complianceModerator.setSmallCap(smallCap);
                this.complianceModerator.setMediumCap(mediumCap);
                this.complianceModerator.setLargeCap(largeCap);
                JOptionPane.showMessageDialog(this, "Market Standards Updated");
                txtSmallCap.setText("");
                txtMediumCap.setText("");
                txtLargeCap.setText("");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Values must be numbers only!");
            
        }
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        changeScreen(industryStandards);
    }//GEN-LAST:event_jToggleButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allCompanies;
    private javax.swing.JPanel homepage;
    private javax.swing.JPanel industryStandards;
    private javax.swing.JButton jBtngoback;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel listingrequests;
    private javax.swing.JPanel managerDetails;
    private javax.swing.JTable tableRegisterComp;
    private javax.swing.JTable tblAllCompanies;
    private javax.swing.JTable tblInvManager;
    private javax.swing.JTextField txtLargeCap;
    private javax.swing.JTextField txtMediumCap;
    private javax.swing.JTextField txtSmallCap;
    // End of variables declaration//GEN-END:variables

    private void populateLiscensingTable() {
        DefaultTableModel model = (DefaultTableModel) tableRegisterComp.getModel();
        model.setRowCount(0);
        for(Company company: this.complianceModerator.getCompanyList()){
            if(company.getLicenseStatus().equals("Pending")){
                Object[] row= new Object[6];
                row[0]=company.getName();
                row[1]=company.getAssets();
                row[2]=company.getLiabilites();
                row[3]=company.getCapital();
                if(company.getInvestmentManager()==null){
                    row[4]="Not Assigned";
                }
                else{
                    row[4]=company.getInvestmentManager().getName();
                }
                row[5]=company.getLicenseStatus();
                model.addRow(row);
            }
        }
    }

    private void changeScreen(JPanel newJPanel) {
        this.removeAll();
        this.add(newJPanel);
        this.revalidate();
        this.repaint();
    }

    private void populateAllCompaniesTable() {
        DefaultTableModel model = (DefaultTableModel) tblAllCompanies.getModel();
        model.setRowCount(0);
        for(Company company: this.complianceModerator.getCompanyList()){
            Object[] row= new Object[7];
            row[0]=company.getName();
            row[1]=company.getCapital();
            row[2]=company.getAssets();
            row[3]=company.getLiabilites();
            row[4]=company.getLicenseStatus();
            row[5]=company.getCompanyManager().getName();
            if(company.getInvestmentManager()==null){
                row[6]="Not Assigned";
            }
            else{
                row[6]=company.getInvestmentManager().getName();
            }
            model.addRow(row);
        }
    }

    private void populateInvestmentManagerTable() {
        DefaultTableModel model = (DefaultTableModel) tblInvManager.getModel();
        model.setRowCount(0);
        for(InvestmentManager investmentManager: this.complianceModerator.getInvestmentManagers()){
            Object[] row = new Object[2];
            row[0]=investmentManager.getName();
            if(investmentManager.getAssignedCompany()==null){
                row[1]="Not Assigned";
            }
            else{
                row[1]=investmentManager.getAssignedCompany().getName();
            }
            model.addRow(row);
        }
    }

}
