/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.Moderator;


import business.Company.Company;
import business.Investor.StockHoldings;
import business.Listing.ListingRequest;
import business.Stocks.Stock;
import business.Stocks.StockMarketModerator;
import business.TheBusiness.Business;
import business.UserAccount.UserAccount;
import dataContext.DataContext;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author revanth
 */
public class StockMarketModeratorJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    UserAccount account;
    Business business;
    StockMarketModerator stockMarketModerator;
    Stock selectedStock;
    public StockMarketModeratorJPanel(JPanel userProcessContainer, UserAccount account, Business business) {
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.business=business;
        this.stockMarketModerator = (StockMarketModerator) account.getUser();
        initComponents();
        populateTableShares();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        MarketModeratorHomepage = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLblMarketmanagement = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ListingRequestJPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listingRequestTable = new javax.swing.JTable();
        jBtnapprove = new javax.swing.JButton();
        jbtndecline = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jLblMarketmanagement1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DelistingRequest = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableManagers2 = new javax.swing.JTable();
        jbtndecline1 = new javax.swing.JButton();
        jBtnapprove1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLblMarketmanagement2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        MarketManagementJPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableShares = new javax.swing.JTable();
        jLblCompany = new javax.swing.JLabel();
        jLblprice = new javax.swing.JLabel();
        jLblmarketcap = new javax.swing.JLabel();
        jBtnupdate = new javax.swing.JButton();
        jTxtmarketcap = new javax.swing.JTextField();
        jtxtprice = new javax.swing.JTextField();
        jTxtCompany = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLblMarketmanagement3 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Listing Request");

        setBackground(new java.awt.Color(153, 0, 255));
        setLayout(new java.awt.CardLayout());

        MarketModeratorHomepage.setBackground(new java.awt.Color(255, 255, 255));
        MarketModeratorHomepage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setBackground(new java.awt.Color(85, 65, 118));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("View Listing Request");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        MarketModeratorHomepage.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 180, 180, 38));

        jButton3.setBackground(new java.awt.Color(85, 65, 118));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Market Management");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        MarketModeratorHomepage.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 167, 38));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dashboard");
        MarketModeratorHomepage.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, -1, 40));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1300, 80));

        jLblMarketmanagement.setBackground(new java.awt.Color(255, 255, 255));
        jLblMarketmanagement.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLblMarketmanagement.setForeground(new java.awt.Color(85, 65, 119));
        jLblMarketmanagement.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMarketmanagement.setText("Securities and Exchange Board");
        jPanel1.add(jLblMarketmanagement);

        MarketModeratorHomepage.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 80));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/At the office-amico.png"))); // NOI18N
        MarketModeratorHomepage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 580, 400));

        add(MarketModeratorHomepage, "card2");

        ListingRequestJPanel.setBackground(new java.awt.Color(255, 255, 255));
        ListingRequestJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listingRequestTable.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        listingRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "RequestId", "Company Name", "Price Per Share", "Stock Qty", "Market Cap", "Approval Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(listingRequestTable);

        ListingRequestJPanel.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 759, 190));

        jBtnapprove.setBackground(new java.awt.Color(85, 65, 118));
        jBtnapprove.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jBtnapprove.setForeground(new java.awt.Color(255, 255, 255));
        jBtnapprove.setText("Approve");
        jBtnapprove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnapproveActionPerformed(evt);
            }
        });
        ListingRequestJPanel.add(jBtnapprove, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 100, 40));

        jbtndecline.setBackground(new java.awt.Color(85, 65, 118));
        jbtndecline.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jbtndecline.setForeground(new java.awt.Color(255, 255, 255));
        jbtndecline.setText("Decline");
        jbtndecline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtndeclineActionPerformed(evt);
            }
        });
        ListingRequestJPanel.add(jbtndecline, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 440, 110, 40));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel6.setText("Listing Requests");
        ListingRequestJPanel.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 330, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Requests List:");
        ListingRequestJPanel.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 190, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton4.setBackground(new java.awt.Color(85, 65, 119));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("<< Back");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLblMarketmanagement1.setBackground(new java.awt.Color(255, 255, 255));
        jLblMarketmanagement1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLblMarketmanagement1.setForeground(new java.awt.Color(85, 65, 119));
        jLblMarketmanagement1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMarketmanagement1.setText("Securities and Exchange Commission");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton4)
                .addGap(105, 105, 105)
                .addComponent(jLblMarketmanagement1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblMarketmanagement1)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        ListingRequestJPanel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1070, 80));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Statistics-bro.png"))); // NOI18N
        ListingRequestJPanel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 390, 580, 400));

        add(ListingRequestJPanel, "card3");

        DelistingRequest.setBackground(new java.awt.Color(255, 255, 255));
        DelistingRequest.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableManagers2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tableManagers2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Company Name", "Price Per Share", "Stock Qty", "Market Cap", "Approval Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tableManagers2);

        DelistingRequest.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, 759, 192));

        jbtndecline1.setBackground(new java.awt.Color(85, 65, 118));
        jbtndecline1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtndecline1.setForeground(new java.awt.Color(255, 255, 255));
        jbtndecline1.setText("Decline");
        DelistingRequest.add(jbtndecline1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 114, 44));

        jBtnapprove1.setBackground(new java.awt.Color(85, 65, 118));
        jBtnapprove1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnapprove1.setForeground(new java.awt.Color(255, 255, 255));
        jBtnapprove1.setText("Approve");
        jBtnapprove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnapprove1ActionPerformed(evt);
            }
        });
        DelistingRequest.add(jBtnapprove1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 400, 108, 44));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel8.setText("Requests List:");
        DelistingRequest.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Delisting Requests");
        DelistingRequest.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 90, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jLblMarketmanagement2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLblMarketmanagement2.setForeground(new java.awt.Color(85, 65, 119));
        jLblMarketmanagement2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMarketmanagement2.setText("Securities and Exchange Board");

        jButton5.setBackground(new java.awt.Color(85, 65, 119));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("<< Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 303, Short.MAX_VALUE)
                .addComponent(jLblMarketmanagement2)
                .addGap(171, 171, 171))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblMarketmanagement2)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );

        DelistingRequest.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Downfall-bro.png"))); // NOI18N
        DelistingRequest.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, 580, 400));

        add(DelistingRequest, "card4");

        MarketManagementJPanel.setBackground(new java.awt.Color(255, 255, 255));
        MarketManagementJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableShares.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        tableShares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Company Name", "Price Per Share", "Stock Qty", "Market Cap", "Assets", "Liabilities"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableShares.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableSharesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableShares);

        MarketManagementJPanel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 810, 192));

        jLblCompany.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLblCompany.setText("Company:");
        MarketManagementJPanel.add(jLblCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 70, 22));

        jLblprice.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLblprice.setText("Price:");
        MarketManagementJPanel.add(jLblprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 390, 40, 34));

        jLblmarketcap.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLblmarketcap.setText("Market Cap:");
        MarketManagementJPanel.add(jLblmarketcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 90, 34));

        jBtnupdate.setBackground(new java.awt.Color(85, 65, 118));
        jBtnupdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jBtnupdate.setForeground(new java.awt.Color(255, 255, 255));
        jBtnupdate.setText("Update");
        jBtnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnupdateActionPerformed(evt);
            }
        });
        MarketManagementJPanel.add(jBtnupdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 450, 130, 40));

        jTxtmarketcap.setEditable(false);
        jTxtmarketcap.setBackground(new java.awt.Color(255, 255, 255));
        MarketManagementJPanel.add(jTxtmarketcap, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 390, 180, 40));

        jtxtprice.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jtxtpriceInputMethodTextChanged(evt);
            }
        });
        jtxtprice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtpriceActionPerformed(evt);
            }
        });
        MarketManagementJPanel.add(jtxtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 180, 40));

        jTxtCompany.setEditable(false);
        jTxtCompany.setBackground(new java.awt.Color(255, 255, 255));
        jTxtCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCompanyActionPerformed(evt);
            }
        });
        MarketManagementJPanel.add(jTxtCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 180, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Market Management");
        MarketManagementJPanel.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Listed Companies:");
        MarketManagementJPanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLblMarketmanagement3.setBackground(new java.awt.Color(255, 255, 255));
        jLblMarketmanagement3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLblMarketmanagement3.setForeground(new java.awt.Color(85, 65, 119));
        jLblMarketmanagement3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMarketmanagement3.setText("Securities and Exchange Board");

        jButton6.setBackground(new java.awt.Color(85, 65, 118));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("<< Back");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jButton6)
                .addGap(127, 127, 127)
                .addComponent(jLblMarketmanagement3)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblMarketmanagement3)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        MarketManagementJPanel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, 80));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Presentation-cuate.png"))); // NOI18N
        MarketManagementJPanel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 530, 350));

        add(MarketManagementJPanel, "card5");
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCompanyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCompanyActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        updateJPanel(ListingRequestJPanel);
        populateListingTable();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBtnapproveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnapproveActionPerformed
        
        Stock stock = new Stock();
        if(listingRequestTable.getSelectedRow()==-1)
        {
                JOptionPane.showMessageDialog(this, "Please select a row to process");
                return;

        }
        
        String selectedCompanyName=String.valueOf(listingRequestTable.getValueAt(listingRequestTable.getSelectedRow(), 1));
        Company selectedCompany = this.business.getCompliance().getComplianceModerator().getCompanyByName(selectedCompanyName);
        stock.setCompany(selectedCompany);
        selectedCompany.setLicenseRequestStatus("Listed");
        ListingRequest selectedRequest = this.stockMarketModerator.getListingRequestById(Integer.parseInt(String.valueOf(listingRequestTable.getValueAt(listingRequestTable.getSelectedRow(), 0))));
        selectedRequest.setStatus("Listed");
        selectedCompany.setListingRequestStatus("Listed");
        
        stock.setPrice(selectedRequest.getSharePrice());
        stock.setStockQuantity(selectedRequest.getTotalShares());
        stock.setAvailableQuantity(selectedRequest.getTotalShares());
        this.business.getMarket().getStockMarket().getStockList().add(stock);
        this.stockMarketModerator.getListingRequestList().remove(selectedRequest);
        
        stock.getPriceHistory().add(stock.getPrice());
        JOptionPane.showMessageDialog(this, "Listing Request Approved!");
        business = DataContext.setBusiness(business);
        populateListingTable();
    }//GEN-LAST:event_jBtnapproveActionPerformed

    private void tableSharesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableSharesMouseClicked
        
        this.selectedStock = this.business.getMarket().getStockMarket().getStockByName(String.valueOf(tableShares.getValueAt(tableShares.getSelectedRow(), 0)));
        jTxtCompany.setText(selectedStock.getCompany().getName());
        jtxtprice.setText(String.valueOf(selectedStock.getPrice()));
        jTxtmarketcap.setText(String.valueOf(selectedStock.getCompany().getCapital()));
        jBtnupdate.setEnabled(true);
        
    }//GEN-LAST:event_tableSharesMouseClicked

    private void jBtnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnupdateActionPerformed
        double marketCap = Double.parseDouble(jtxtprice.getText())*this.selectedStock.getStockQuantity();
        this.selectedStock.getCompany().CalculateMarkertCap(marketCap);
        
        this.selectedStock.setPrice(Double.parseDouble(jtxtprice.getText()));
        this.selectedStock.getPriceHistory().add(Double.parseDouble(jtxtprice.getText()));
        
        double marketIndex = calculateMarketIndex();
//        this.business.getMarket().getStockMarket().updateMarketMetrics(marketIndex);
        updateAllEquityPrice();
        
        populateTableShares();
        jTxtmarketcap.setText(String.valueOf(selectedStock.getCompany().getCapital()));
        JOptionPane.showMessageDialog(this, "Updated!");
        clearfeilds();
        jBtnupdate.setEnabled(false);
    }//GEN-LAST:event_jBtnupdateActionPerformed

    private void jtxtpriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtpriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtpriceActionPerformed

    private void jtxtpriceInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jtxtpriceInputMethodTextChanged
        double marketCap = Double.parseDouble(jtxtprice.getText())*this.selectedStock.getStockQuantity();
        jTxtmarketcap.setText(String.valueOf(marketCap));
    }//GEN-LAST:event_jtxtpriceInputMethodTextChanged

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        updateJPanel(MarketManagementJPanel);
        jBtnupdate.setEnabled(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        updateJPanel(MarketModeratorHomepage);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        updateJPanel(MarketModeratorHomepage);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        updateJPanel(MarketModeratorHomepage);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jbtndeclineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtndeclineActionPerformed
       
        
        Stock stock = new Stock();
        if(listingRequestTable.getSelectedRow()==-1)
        {
                JOptionPane.showMessageDialog(this, "Please select a row to process");
                return;

        }
        
        String selectedCompanyName=String.valueOf(listingRequestTable.getValueAt(listingRequestTable.getSelectedRow(), 1));
        Company selectedCompany = this.business.getCompliance().getComplianceModerator().getCompanyByName(selectedCompanyName);
        selectedCompany.setLicenseRequestStatus("Rejected");
        ListingRequest selectedRequest = this.stockMarketModerator.getListingRequestById(Integer.parseInt(String.valueOf(listingRequestTable.getValueAt(listingRequestTable.getSelectedRow(), 0))));
        selectedRequest.setStatus("Reject");
        this.stockMarketModerator.getListingRequestList().remove(selectedRequest);
        JOptionPane.showMessageDialog(this, "Listing Request Rejected Successfully!");
        business = DataContext.setBusiness(business);
        populateListingTable();
    }//GEN-LAST:event_jbtndeclineActionPerformed

    private void jBtnapprove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnapprove1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnapprove1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DelistingRequest;
    private javax.swing.JPanel ListingRequestJPanel;
    private javax.swing.JPanel MarketManagementJPanel;
    private javax.swing.JPanel MarketModeratorHomepage;
    private javax.swing.JButton jBtnapprove;
    private javax.swing.JButton jBtnapprove1;
    private javax.swing.JButton jBtnupdate;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblCompany;
    private javax.swing.JLabel jLblMarketmanagement;
    private javax.swing.JLabel jLblMarketmanagement1;
    private javax.swing.JLabel jLblMarketmanagement2;
    private javax.swing.JLabel jLblMarketmanagement3;
    private javax.swing.JLabel jLblmarketcap;
    private javax.swing.JLabel jLblprice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTxtCompany;
    private javax.swing.JTextField jTxtmarketcap;
    private javax.swing.JButton jbtndecline;
    private javax.swing.JButton jbtndecline1;
    private javax.swing.JTextField jtxtprice;
    private javax.swing.JTable listingRequestTable;
    private javax.swing.JTable tableManagers2;
    private javax.swing.JTable tableShares;
    // End of variables declaration//GEN-END:variables

    private void populateTableShares() {
        int rc = tableShares.getRowCount();
        int i;
        for (i = rc - 1; i >= 0; i--) {
            ((DefaultTableModel) tableShares.getModel()).removeRow(i);
        }
        DefaultTableModel model = (DefaultTableModel) tableShares.getModel();
        model.setRowCount(0);
        for(Stock stock: this.business.getMarket().getStockMarket().getStockList()){
            Object[] row= new Object[6];
            row[0]=stock.getCompany().getName();
            row[1]=stock.getPrice();
            row[2]=stock.getStockQuantity();
            row[3]=stock.getCompany().getCapital();
            row[4]=stock.getCompany().getAssets();
            row[5]=stock.getCompany().getLiabilites();
            model.addRow(row);
        }
    }

    private void updateJPanel(JPanel jPanel) {
        this.removeAll();
        this.add(jPanel);
        this.revalidate();
        this.repaint();
    }

    private void populateListingTable() {
        DefaultTableModel model = (DefaultTableModel) listingRequestTable.getModel();
        model.setRowCount(0);
        for(ListingRequest listingRequest: this.stockMarketModerator.getListingRequestList()){
            Object[] row= new Object[6];
            row[0]=listingRequest.getRequestId();
            row[1]=listingRequest.getCompany().getName();
            row[2]=listingRequest.getSharePrice();
            row[3]=listingRequest.getTotalShares();
            row[4]=listingRequest.getCompany().getCapital();
            row[5]=listingRequest.getStatus();
            model.addRow(row);
        }
    }
    private void updateAllEquityPrice() {
        for(Company company: this.business.getCompliance().getComplianceModerator().getCompanyList()){
            for(StockHoldings stockHoldings:company.getStockHoldings()){
                if(stockHoldings.getStock()==this.selectedStock){
                    for(Stock stock:this.business.getMarket().getStockMarket().getStockList()){
                        if(company==stock.getCompany()){
                            stock.calculateAndSetPrice();
                        }
                    }
                }
            }
        }
    }
    public double calculateMarketIndex(){
        double marketIndex=0;
        int indexWeightage=0;
        for(Stock equity:this.business.getMarket().getStockMarket().getStockList()){
            if(equity.getCompany().getCapital()<this.business.getCompliance().getComplianceModerator().getSmallCap()){
                marketIndex+=equity.getPrice();
                indexWeightage+=1;
            }
            else if(equity.getCompany().getCapital()<this.business.getCompliance().getComplianceModerator().getMediumCap()){
                marketIndex+=(equity.getPrice()*2);
                indexWeightage+=2;
            }
            else{
                marketIndex+=(equity.getPrice()*3);
                indexWeightage+=3;
            }
        }
        return marketIndex/indexWeightage;
    }

    private void clearfeilds() {
        jTxtCompany.setText("");
        jtxtprice.setText("");
        jTxtmarketcap.setText("");       
        }
}
