/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.Main;

import business.Broker.BrokerageModerator;
import business.Commodities.CommodityBroker;
import business.Commodities.CommodityModerator;
import business.Company.CompanyManager;
import business.Compliance.ComplianceModerator;
import business.InvestmentManager.InvestmentManager;
import business.Investor.Investor;
import business.MarketAnalyst.MarketAnalyst;
import business.Roles.Role;
import business.Stocks.StockBroker;
import business.TheBusiness.Business;
import business.UserAccount.User;
import business.UserAccount.UserAccount;
import dataContext.DataContext;

import static java.time.InstantSource.system;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userInterface.WorkAreas.BrokerageModeratorRole;
import userInterface.WorkAreas.CommodityBrokerRole;
import userInterface.WorkAreas.CommodityModeratorRole;
import userInterface.WorkAreas.CompanyManagerRole;
import userInterface.WorkAreas.ComplianceModeratorRole;
import userInterface.WorkAreas.InvestmentManagerRole;
import userInterface.WorkAreas.InvestorRole;
import userInterface.WorkAreas.MarketAnalystRole;
import userInterface.WorkAreas.StockBrokerRole;
import userInterface.WorkAreas.StockMarketModeratorRole;

/**
 *
 * @author revanth
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    
    private Business business;
    User selectedUser;
    Role role;
    private DataContext dataContext;
    
    public MainJFrame() {
        initComponents();
        setContainer(homeJPanel);
        dataContext = DataContext.getInstance();
        business = dataContext.retrieveBusiness();
        signUpJPanel.setVisible(false);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        container = new javax.swing.JPanel();
        signInJPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        txtTitle2 = new javax.swing.JLabel();
        jPasswordField4 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        homeJPanel = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        loginAndSignUp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        txtTitle = new javax.swing.JLabel();
        jlblnoaccount = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        signUpJPanel = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPasswordField3 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        rolesPanal = new javax.swing.JPanel();
        btnDayTrader = new javax.swing.JButton();
        btnCommodityBroker = new javax.swing.JButton();
        btnRetailInvestor = new javax.swing.JButton();
        btnCommodityMarketModerator = new javax.swing.JButton();
        btnEquityBroker = new javax.swing.JButton();
        btnEquityMarketModerator = new javax.swing.JButton();
        btnBrokersCommissionAdmin = new javax.swing.JButton();
        btnLicensingCommissionAdmin = new javax.swing.JButton();
        btnCompanyManager = new javax.swing.JButton();
        btnInvestmentsManager = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSplitPane2.setBackground(new java.awt.Color(0, 51, 51));
        jSplitPane2.setDividerLocation(250);

        container.setBackground(new java.awt.Color(255, 255, 255));
        container.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        container.setLayout(new java.awt.CardLayout());

        signInJPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setBackground(new java.awt.Color(153, 0, 255));
        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Username:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Password:");

        txtTitle2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtTitle2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle2.setText("PORTAL");

        jButton3.setBackground(new java.awt.Color(85, 65, 118));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Log In");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Login-amico.png"))); // NOI18N

        javax.swing.GroupLayout signInJPanelLayout = new javax.swing.GroupLayout(signInJPanel);
        signInJPanel.setLayout(signInJPanelLayout);
        signInJPanelLayout.setHorizontalGroup(
            signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtTitle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(signInJPanelLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                        .addComponent(jPasswordField4))
                    .addGroup(signInJPanelLayout.createSequentialGroup()
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addContainerGap(1272, Short.MAX_VALUE))
        );
        signInJPanelLayout.setVerticalGroup(
            signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signInJPanelLayout.createSequentialGroup()
                .addComponent(txtTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(signInJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(382, Short.MAX_VALUE))
        );

        container.add(signInJPanel, "card3");

        homeJPanel.setBackground(new java.awt.Color(255, 255, 255));
        homeJPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setBackground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Welcome.png"))); // NOI18N
        homeJPanel.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 820, 990));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 65, 118));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("EquityElite");
        homeJPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1210, 80));

        container.add(homeJPanel, "card4");

        loginAndSignUp.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel3.setText("Username:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel4.setText("Password:");

        jButton1.setBackground(new java.awt.Color(85, 65, 118));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Log In");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtTitle.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        txtTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtTitle.setText("PORTAL");

        jlblnoaccount.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jlblnoaccount.setText("Don't have account?");

        jButton6.setBackground(new java.awt.Color(85, 65, 118));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Sign Up");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        signUpJPanel.setBackground(new java.awt.Color(255, 255, 255));
        signUpJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sign Up", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jButton2.setBackground(new java.awt.Color(85, 65, 118));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel8.setText("Confirm Password: *");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("Password: *");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel6.setText("Username: *");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setText("Name: *");

        javax.swing.GroupLayout signUpJPanelLayout = new javax.swing.GroupLayout(signUpJPanel);
        signUpJPanel.setLayout(signUpJPanelLayout);
        signUpJPanelLayout.setHorizontalGroup(
            signUpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 522, Short.MAX_VALUE)
            .addGroup(signUpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signUpJPanelLayout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addGroup(signUpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(signUpJPanelLayout.createSequentialGroup()
                            .addGap(180, 180, 180)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signUpJPanelLayout.createSequentialGroup()
                            .addGroup(signUpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addComponent(jLabel5)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8))
                            .addGap(18, 18, 18)
                            .addGroup(signUpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addContainerGap(106, Short.MAX_VALUE)))
        );
        signUpJPanelLayout.setVerticalGroup(
            signUpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 327, Short.MAX_VALUE)
            .addGroup(signUpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(signUpJPanelLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(signUpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(signUpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(signUpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7))
                    .addGap(18, 18, 18)
                    .addGroup(signUpJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jPasswordField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGap(31, 31, 31)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(50, Short.MAX_VALUE)))
        );

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Sign up-amico.png"))); // NOI18N

        javax.swing.GroupLayout loginAndSignUpLayout = new javax.swing.GroupLayout(loginAndSignUp);
        loginAndSignUp.setLayout(loginAndSignUpLayout);
        loginAndSignUpLayout.setHorizontalGroup(
            loginAndSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginAndSignUpLayout.createSequentialGroup()
                .addGroup(loginAndSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 970, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(loginAndSignUpLayout.createSequentialGroup()
                        .addGroup(loginAndSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(loginAndSignUpLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(loginAndSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginAndSignUpLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, loginAndSignUpLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(loginAndSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(loginAndSignUpLayout.createSequentialGroup()
                                                .addComponent(jlblnoaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jPasswordField1)))))
                            .addGroup(loginAndSignUpLayout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addComponent(signUpJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addContainerGap(996, Short.MAX_VALUE))
        );
        loginAndSignUpLayout.setVerticalGroup(
            loginAndSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginAndSignUpLayout.createSequentialGroup()
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(loginAndSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginAndSignUpLayout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(loginAndSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(loginAndSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(loginAndSignUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblnoaccount, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(signUpJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(loginAndSignUpLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(318, Short.MAX_VALUE))
        );

        container.add(loginAndSignUp, "card2");

        jSplitPane2.setRightComponent(container);

        rolesPanal.setBackground(new java.awt.Color(255, 255, 255));

        btnDayTrader.setBackground(new java.awt.Color(85, 65, 118));
        btnDayTrader.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDayTrader.setForeground(new java.awt.Color(255, 255, 255));
        btnDayTrader.setText("Market Analyst");
        btnDayTrader.setBorder(null);
        btnDayTrader.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDayTraderActionPerformed(evt);
            }
        });

        btnCommodityBroker.setBackground(new java.awt.Color(85, 65, 118));
        btnCommodityBroker.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCommodityBroker.setForeground(new java.awt.Color(255, 255, 255));
        btnCommodityBroker.setText("Commodity Broker");
        btnCommodityBroker.setBorder(null);
        btnCommodityBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommodityBrokerActionPerformed(evt);
            }
        });

        btnRetailInvestor.setBackground(new java.awt.Color(85, 65, 118));
        btnRetailInvestor.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRetailInvestor.setForeground(new java.awt.Color(255, 255, 255));
        btnRetailInvestor.setText("Investor");
        btnRetailInvestor.setBorder(null);
        btnRetailInvestor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetailInvestorActionPerformed(evt);
            }
        });

        btnCommodityMarketModerator.setBackground(new java.awt.Color(85, 65, 118));
        btnCommodityMarketModerator.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCommodityMarketModerator.setForeground(new java.awt.Color(255, 255, 255));
        btnCommodityMarketModerator.setText("Commodity Market Moderator");
        btnCommodityMarketModerator.setBorder(null);
        btnCommodityMarketModerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCommodityMarketModeratorActionPerformed(evt);
            }
        });

        btnEquityBroker.setBackground(new java.awt.Color(85, 65, 118));
        btnEquityBroker.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEquityBroker.setForeground(new java.awt.Color(255, 255, 255));
        btnEquityBroker.setText("Stock Broker");
        btnEquityBroker.setBorder(null);
        btnEquityBroker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquityBrokerActionPerformed(evt);
            }
        });

        btnEquityMarketModerator.setBackground(new java.awt.Color(85, 65, 118));
        btnEquityMarketModerator.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEquityMarketModerator.setForeground(new java.awt.Color(255, 255, 255));
        btnEquityMarketModerator.setText("Security Board");
        btnEquityMarketModerator.setBorder(null);
        btnEquityMarketModerator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEquityMarketModeratorActionPerformed(evt);
            }
        });

        btnBrokersCommissionAdmin.setBackground(new java.awt.Color(85, 65, 118));
        btnBrokersCommissionAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBrokersCommissionAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnBrokersCommissionAdmin.setText("Brokers Commission Admin");
        btnBrokersCommissionAdmin.setBorder(null);
        btnBrokersCommissionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrokersCommissionAdminActionPerformed(evt);
            }
        });

        btnLicensingCommissionAdmin.setBackground(new java.awt.Color(85, 65, 118));
        btnLicensingCommissionAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnLicensingCommissionAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnLicensingCommissionAdmin.setText("Compliance Board");
        btnLicensingCommissionAdmin.setBorder(null);
        btnLicensingCommissionAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLicensingCommissionAdminActionPerformed(evt);
            }
        });

        btnCompanyManager.setBackground(new java.awt.Color(85, 65, 118));
        btnCompanyManager.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCompanyManager.setForeground(new java.awt.Color(255, 255, 255));
        btnCompanyManager.setText("Company Manager");
        btnCompanyManager.setBorder(null);
        btnCompanyManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompanyManagerActionPerformed(evt);
            }
        });

        btnInvestmentsManager.setBackground(new java.awt.Color(85, 65, 118));
        btnInvestmentsManager.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnInvestmentsManager.setForeground(new java.awt.Color(255, 255, 255));
        btnInvestmentsManager.setText("Investments Manager");
        btnInvestmentsManager.setBorder(null);
        btnInvestmentsManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvestmentsManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rolesPanalLayout = new javax.swing.GroupLayout(rolesPanal);
        rolesPanal.setLayout(rolesPanalLayout);
        rolesPanalLayout.setHorizontalGroup(
            rolesPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rolesPanalLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(rolesPanalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rolesPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetailInvestor, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rolesPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnEquityMarketModerator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCommodityMarketModerator, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLicensingCommissionAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCompanyManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInvestmentsManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEquityBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCommodityBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrokersCommissionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDayTrader, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rolesPanalLayout.setVerticalGroup(
            rolesPanalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rolesPanalLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnRetailInvestor, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEquityBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEquityMarketModerator, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCommodityBroker, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCommodityMarketModerator, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBrokersCommissionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCompanyManager, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnInvestmentsManager, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLicensingCommissionAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDayTrader, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(389, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(rolesPanal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1942, Short.MAX_VALUE)
                .addGap(54, 54, 54))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCommodityBrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommodityBrokerActionPerformed
        this.selectedUser=new CommodityBroker();
        this.role = new CommodityBrokerRole();
        setRightPanalSignInUp(this.role, "Commodity Broker");
        business = DataContext.setBusiness(business);
    }//GEN-LAST:event_btnCommodityBrokerActionPerformed

    private void btnDayTraderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDayTraderActionPerformed
        this.selectedUser=new MarketAnalyst();
        this.role=new MarketAnalystRole();
        setRightPanalSignIn(this.role, "Market Analyst");
        DataContext.setBusiness(business);
    }//GEN-LAST:event_btnDayTraderActionPerformed

    private void btnCommodityMarketModeratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCommodityMarketModeratorActionPerformed
        this.selectedUser = new CommodityModerator();
        this.role = new CommodityModeratorRole();
        setRightPanalSignIn(this.role, "Commodity Futures Trading Commission");
        business = DataContext.setBusiness(business);
    }//GEN-LAST:event_btnCommodityMarketModeratorActionPerformed

    private void btnEquityBrokerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquityBrokerActionPerformed
        this.selectedUser=new StockBroker();
        this.role=new StockBrokerRole();
        signUpJPanel.setVisible(false);
        setRightPanalSignInUp(this.role, "Stock Broker");
        DataContext.setBusiness(business);
    }//GEN-LAST:event_btnEquityBrokerActionPerformed

    private void btnEquityMarketModeratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEquityMarketModeratorActionPerformed
        this.selectedUser=new CompanyManager();
        this.role=new StockMarketModeratorRole();
        signUpJPanel.setVisible(false);
        setRightPanalSignIn(this.role, "Securities and Exchange Commission");
        dataContext.setBusiness(business);
    }//GEN-LAST:event_btnEquityMarketModeratorActionPerformed

    private void btnBrokersCommissionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrokersCommissionAdminActionPerformed
        this.selectedUser=new BrokerageModerator();
        this.role=new BrokerageModeratorRole();
        signUpJPanel.setVisible(false);
        setRightPanalSignIn(this.role, "Brokers Commmission Admin");
        DataContext.setBusiness(business);
    }//GEN-LAST:event_btnBrokersCommissionAdminActionPerformed

    private void btnLicensingCommissionAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLicensingCommissionAdminActionPerformed
        this.selectedUser=new ComplianceModerator();
        this.role=new ComplianceModeratorRole();
        signUpJPanel.setVisible(false);
        setRightPanalSignIn(this.role, "Compliance Moderator");
        dataContext.setBusiness(business);
    }//GEN-LAST:event_btnLicensingCommissionAdminActionPerformed

    private void btnCompanyManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompanyManagerActionPerformed
        this.selectedUser=new CompanyManager();
        this.role=new CompanyManagerRole();
        signUpJPanel.setVisible(false);
        setRightPanalSignInUp(this.role, "Company Manager");
        dataContext.setBusiness(business);
    }//GEN-LAST:event_btnCompanyManagerActionPerformed

    private void btnInvestmentsManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvestmentsManagerActionPerformed
        this.selectedUser=new InvestmentManager();
        this.role=new InvestmentManagerRole();
        signUpJPanel.setVisible(false);
        setRightPanalSignInUp(this.role, "Investment Manager");
        dataContext.setBusiness(business);
    }//GEN-LAST:event_btnInvestmentsManagerActionPerformed

    private void btnRetailInvestorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetailInvestorActionPerformed
        this.selectedUser = new Investor();
        this.role = new InvestorRole();
        signUpJPanel.setVisible(false);
        setRightPanalSignInUp(this.role, "Investor");
        dataContext.setBusiness(business);
    }//GEN-LAST:event_btnRetailInvestorActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        char[] password=jPasswordField4.getPassword();
        String passwordString = new String(password);
        UserAccount user=business.getUserDirectory().authenticateUser(jTextField5.getText(), passwordString);
        if(user!=null && (user.getRole().getClass()==this.role.getClass())){
            setContainer(user.getRole().createWorkArea(container, user, business));
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid Username or Password!");
        }
        jTextField5.setText("");
        jPasswordField4.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        char[] password=jPasswordField1.getPassword();
        String passwordString = new String(password);
        UserAccount user=business.getUserDirectory().authenticateUser(jTextField2.getText(), passwordString);
        if(user!=null){
            System.out.println("User authenticated");
        }
        if(user!=null && (user.getRole().getClass()==this.role.getClass())){
            setContainer(user.getRole().createWorkArea(container, user, business));
            jTextField2.setText("");
            jPasswordField1.setText(""); 
        }
        else{
            JOptionPane.showMessageDialog(this, "Invalid Username or Password!");
            jTextField2.setText("");
            jPasswordField1.setText("");        
        }
        jTextField2.setText("");
        jPasswordField1.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        signUpJPanel.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        char[] password=jPasswordField2.getPassword();
        String passwordString = new String(password);
        char[] confirmPassword=jPasswordField3.getPassword();
        String confirmPasswordString = new String(confirmPassword);
        String username=jTextField4.getText();
        if(validatePassword(passwordString)){
            if(!passwordString.equals(confirmPasswordString)){
                JOptionPane.showMessageDialog(this, "Passwords Do Not Match");
            }
            else{
                selectedUser.setName(jTextField3.getText());
                selectedUser.setUserId(business.getUserCount());
                business.setUserCount(business.getUserCount()+1);
                if(this.business.getUserDirectory().checkIfUsernameIsUnique(username)){
                    UserAccount user=this.business.getUserDirectory().createUserAccount(username, passwordString, selectedUser, role);
//                    if(role instanceof CommodityBrokerRole){
//                        this.system.getBrokerage().getCommodityBrokersDirectory().add((CommodityBroker)selectedUser);
//                    }
//                    else if(role instanceof EquityBrokerRole){
//                        this.system.getBrokerage().getEquityBrokersDirectory().add((EquityBroker)selectedUser);
//                    }
                    if(role instanceof InvestorRole){
                        business.getInvestorDirectory().getInvestorDirectory().add((Investor)selectedUser);
                    }
                    else if(role instanceof CompanyManagerRole){
                        business.getCompliance().getComplianceModerator().getCompanyManagers().add((CompanyManager)selectedUser);
                    }
                    else if(role instanceof InvestmentManagerRole){
                        business.getCompliance().getComplianceModerator().getInvestmentManagers().add((InvestmentManager)selectedUser);
                    }
                    else if(role instanceof CommodityBrokerRole){
                        business.getBrokerage().getCommodityBrokers().add((CommodityBroker)selectedUser);
                    }
//                    else if(role instanceof InvestmentManagerRole
//                        this.system.getEstablishment().getEstablishmentsModerator().getInvestmentManagerDirectory().add((InvestmentManager)selectedUser);
//                    }
//                    else if(role instanceof CompanyManagerRole){
//                        this.system.getEstablishment().getEstablishmentsModerator().getCompanyManagerDirectory().add((CompanyManager)selectedUser);
//                    }
//                    else{
//                        this.system.getInvestor().getDayTraderDirectory().add((DayTrader)selectedUser);
//                    }
                    //JOptionPane.showMessageDialog(this, "User Signed In Successfully.");
                    int result = JOptionPane.showConfirmDialog(this, "User Signed In Successfully. Do you want to login?", "Confirmation", JOptionPane.YES_NO_OPTION);

                    if (result == JOptionPane.YES_OPTION) {
                        setContainer(user.getRole().createWorkArea(container, user, business));
                    }
                    setContainer(user.getRole().createWorkArea(container, user, business));
                    jTextField2.setText("");
                    jPasswordField1.setText("");
                    jPasswordField2.setText("");
                    jPasswordField3.setText("");
                    jTextField4.setText("");
                    jTextField3.setText("");
                    jTextField5.setText("");
                    
            }
        }
        }else{
            JOptionPane.showMessageDialog(this, "Password too weak!");
        }
        jTextField3.setText("");
        jTextField4.setText("");
        jPasswordField2.setText("");
        jPasswordField3.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrokersCommissionAdmin;
    private javax.swing.JButton btnCommodityBroker;
    private javax.swing.JButton btnCommodityMarketModerator;
    private javax.swing.JButton btnCompanyManager;
    private javax.swing.JButton btnDayTrader;
    private javax.swing.JButton btnEquityBroker;
    private javax.swing.JButton btnEquityMarketModerator;
    private javax.swing.JButton btnInvestmentsManager;
    private javax.swing.JButton btnLicensingCommissionAdmin;
    private javax.swing.JButton btnRetailInvestor;
    private javax.swing.JPanel container;
    private javax.swing.JPanel homeJPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JPasswordField jPasswordField4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel jlblnoaccount;
    private javax.swing.JPanel loginAndSignUp;
    private javax.swing.JPanel rolesPanal;
    private javax.swing.JPanel signInJPanel;
    private javax.swing.JPanel signUpJPanel;
    private javax.swing.JLabel txtTitle;
    private javax.swing.JLabel txtTitle2;
    // End of variables declaration//GEN-END:variables

    private void setContainer(JPanel newJPanel) {
        container.removeAll();
        container.add(newJPanel);
        container.revalidate();
        container.repaint();
    }

    private void setRightPanalSignInUp(Role role, String titleText) {
        txtTitle.setText(titleText);
        setContainer(loginAndSignUp);
    }
    
    private void setRightPanalSignIn(Role role, String titleText) {
        txtTitle2.setText(titleText);
        setContainer(signInJPanel);
    }

    private void setRightPanalInvestmentManager(Role role, String investment_Manager) {

        setContainer(loginAndSignUp);
    }
    
    
    private Boolean validatePassword(String password1) {
        String regex = "^(?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{8,20}$";
        Pattern pattern = Pattern.compile(regex);
        Matcher matcher = pattern.matcher(password1);
        return matcher.matches();
    }
}
