/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface.CompanyManager;


import business.Company.Company;
import business.InvestmentManager.InvestmentManager;
import business.Investor.StockHoldings;
import business.Job.JobRequest;
import business.Stocks.Stock;
import business.Stocks.StockBroker;
import business.Stocks.StockPurchaseRequest;
import business.Stocks.StockSellRequest;
import business.TheBusiness.Business;
import business.UserAccount.UserAccount;
import dataContext.DataContext;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author revanth
 */
public class InvestmentsManagerJPanel extends javax.swing.JPanel {

    Business business;
    UserAccount account;
    InvestmentManager investmentManager;
    Stock selectedStock;

    public InvestmentsManagerJPanel(JPanel userProcessContainer, UserAccount account, Business business) {
        this.business = business;
        this.account = account;
        this.investmentManager = (InvestmentManager) account.getUser();
        initComponents();
        jLabel18.setVisible(false);
        jLabel6.setVisible(false);
        jLabel3.setVisible(false);
        txtSalary.setVisible(false);
        txtExperience.setVisible(false);
        jButton3.setVisible(false);
        jLabel29.setVisible(false);
        if (investmentManager.getAssignedCompany() == null) {
            populateJobsTable();
            changeScreen(jPanel2);
            jLabel7.setText(this.investmentManager.getName());
        } else {
            populateHoldingsTable();
            populateBuyRequestsTable();
            populateSellRequestsTable();
            setAvailableBalance(this.investmentManager.getAssignedCompany().getBalance());
            jLabel1.setText(this.investmentManager.getName());
            jLabel2.setText(this.investmentManager.getAssignedCompany().getName());
            changeScreen(jPanel1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        myEquityHoldings = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblJobs = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtExperience = new javax.swing.JTextField();
        txtSalary = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStockListBuy = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnBuyShare1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtShrName = new javax.swing.JLabel();
        txtQtyShare = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAvailableBalance = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton10 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btnSellShare = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtShrName1 = new javax.swing.JLabel();
        txtQtyShare1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        lblCLP1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtAvailableBalance1 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jComboBox4 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        buyRequests2 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel30 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton23 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        sellRequests = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel32 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButton24 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 0, 255));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Assigned Company");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jButton1.setBackground(new java.awt.Color(85, 65, 118));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Sell Shares");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 130, 40));

        myEquityHoldings.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Share", "Quantity", "Buying Price", "Current Price", "Total Invested", "Current Valuation"
            }
        ));
        jScrollPane3.setViewportView(myEquityHoldings);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 729, 145));

        jButton4.setBackground(new java.awt.Color(85, 65, 118));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Buy Shares");
        jButton4.setBorder(null);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 130, 40));

        jButton6.setBackground(new java.awt.Color(85, 65, 118));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Buy Requests");
        jButton6.setBorder(null);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 130, 40));

        jButton7.setBackground(new java.awt.Color(85, 65, 118));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Sell Requests");
        jButton7.setBorder(null);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 400, 130, 40));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 65, 119));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Name");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 964, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(358, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1328, -1));

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Generating new leads-amico.png"))); // NOI18N
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 180, 460, 430));

        add(jPanel1, "card2");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Available Jobs:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 148, -1, -1));

        tblJobs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Company", "Market Cap", "Assets", "Liablilities"
            }
        ));
        jScrollPane1.setViewportView(tblJobs);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 176, 701, 118));

        jButton2.setBackground(new java.awt.Color(85, 65, 118));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Apply");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(316, 306, 98, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Enter Experience:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Enter Expected Salary:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 434, -1, -1));

        txtExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExperienceActionPerformed(evt);
            }
        });
        jPanel2.add(txtExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 200, 30));

        txtSalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSalaryActionPerformed(evt);
            }
        });
        jPanel2.add(txtSalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 200, 30));

        jButton3.setBackground(new java.awt.Color(85, 65, 118));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Submit Application");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 470, 157, 40));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Name");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 30, 244, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 51));
        jLabel16.setText("You are not assigned a company yet!");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 80, -1, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Apply for a job below:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 108, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("<Company name>");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 360, 200, -1));

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Job hunt-amico.png"))); // NOI18N
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 220, 530, 450));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel29.setText("Comany Name:");
        jPanel2.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        add(jPanel2, "card3");

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblStockListBuy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Stock Name", "Current Price", "Market Cap", "P/E ratio"
            }
        ));
        jScrollPane2.setViewportView(tblStockListBuy);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 216, 677, 140));

        jButton5.setBackground(new java.awt.Color(85, 65, 118));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Buy");
        jButton5.setBorder(null);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 374, 106, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Buy Shares:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 188, 170, -1));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setPreferredSize(new java.awt.Dimension(1300, 80));

        jButton9.setBackground(new java.awt.Color(85, 65, 119));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton9.setForeground(new java.awt.Color(255, 255, 255));
        jButton9.setText("<< Back");
        jButton9.setActionCommand("<< Back");
        jButton9.setBorder(null);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1166, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Team goals-rafiki.png"))); // NOI18N
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 250, 530, 450));

        add(jPanel4, "card4");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBuyShare1.setBackground(new java.awt.Color(85, 65, 118));
        btnBuyShare1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuyShare1.setForeground(new java.awt.Color(255, 255, 255));
        btnBuyShare1.setText("Buy");
        btnBuyShare1.setBorder(null);
        btnBuyShare1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyShare1ActionPerformed(evt);
            }
        });
        jPanel3.add(btnBuyShare1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 110, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Quantity:");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        txtShrName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtShrName.setText("Share Name");
        jPanel3.add(txtShrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 100, -1, -1));

        txtQtyShare.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtQtyShareInputMethodTextChanged(evt);
            }
        });
        txtQtyShare.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyShareKeyPressed(evt);
            }
        });
        jPanel3.add(txtQtyShare, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 163, 188, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Calculated Price:");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel21.setText("0.0");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 188, 25));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Available Balance:");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, -1, -1));

        txtAvailableBalance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAvailableBalance.setText("Your Balance");
        jPanel3.add(txtAvailableBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 190, 30));

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 300, 190, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Select Broker:");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 310, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Select Market:");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 190, 30));

        jButton10.setBackground(new java.awt.Color(85, 65, 118));
        jButton10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton10.setForeground(new java.awt.Color(255, 255, 255));
        jButton10.setText("Set");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 163, -1, 30));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setPreferredSize(new java.awt.Dimension(1300, 80));

        jButton11.setBackground(new java.awt.Color(85, 65, 119));
        jButton11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton11.setForeground(new java.awt.Color(255, 255, 255));
        jButton11.setText("<< Back");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jButton11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1328, -1));

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Data analysis-amico.png"))); // NOI18N
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 530, 450));

        add(jPanel3, "card3");

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btnSellShare.setBackground(new java.awt.Color(85, 65, 118));
        btnSellShare.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSellShare.setForeground(new java.awt.Color(255, 255, 255));
        btnSellShare.setText("Sell");
        btnSellShare.setBorder(null);
        btnSellShare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSellShareActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Quantity:");

        txtShrName1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txtShrName1.setText("Share Name");

        txtQtyShare1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtQtyShare1InputMethodTextChanged(evt);
            }
        });
        txtQtyShare1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQtyShare1KeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Calculated Price:");

        lblCLP1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        lblCLP1.setText("0.0");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Available Balance:");

        txtAvailableBalance1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        txtAvailableBalance1.setText("Your Balance");

        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setText("Select Broker:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Select Market:");

        jButton8.setBackground(new java.awt.Color(85, 65, 119));
        jButton8.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton8.setForeground(new java.awt.Color(255, 255, 255));
        jButton8.setText("Set");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel9.setPreferredSize(new java.awt.Dimension(1300, 80));

        jButton12.setBackground(new java.awt.Color(85, 65, 119));
        jButton12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton12.setForeground(new java.awt.Color(255, 255, 255));
        jButton12.setText("<< Back");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1181, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Data analysis-amico.png"))); // NOI18N

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 1306, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(txtShrName1))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel20)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSellShare, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jComboBox2, 0, 165, Short.MAX_VALUE)
                                    .addComponent(jComboBox4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtAvailableBalance1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblCLP1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtQtyShare1, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(11, 11, 11)
                                .addComponent(jButton8)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(txtShrName1)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtQtyShare1)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCLP1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAvailableBalance1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addGap(18, 18, 18)
                        .addComponent(btnSellShare, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(195, 195, 195))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel26)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        add(jPanel6, "card3");

        buyRequests2.setBackground(new java.awt.Color(255, 255, 255));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request Id", "Share", "Quantity", "Price"
            }
        ));
        jScrollPane6.setViewportView(jTable3);

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel30.setText("Equity Buy Requests:");

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jButton23.setBackground(new java.awt.Color(85, 65, 119));
        jButton23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("<< Back");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/Add to Cart-amico.png"))); // NOI18N

        javax.swing.GroupLayout buyRequests2Layout = new javax.swing.GroupLayout(buyRequests2);
        buyRequests2.setLayout(buyRequests2Layout);
        buyRequests2Layout.setHorizontalGroup(
            buyRequests2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(buyRequests2Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(buyRequests2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addContainerGap(364, Short.MAX_VALUE))
        );
        buyRequests2Layout.setVerticalGroup(
            buyRequests2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buyRequests2Layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(buyRequests2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(buyRequests2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel30)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(buyRequests2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel27)))
                .addContainerGap(262, Short.MAX_VALUE))
        );

        add(buyRequests2, "card12");

        sellRequests.setBackground(new java.awt.Color(255, 255, 255));
        sellRequests.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Request Id", "Share", "Quantity", "Price"
            }
        ));
        jScrollPane8.setViewportView(jTable5);

        sellRequests.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 170, 639, 154));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setText("Equity Sell Requests:");
        sellRequests.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, -1, 30));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setToolTipText("");
        jPanel11.setPreferredSize(new java.awt.Dimension(1300, 80));

        jButton24.setBackground(new java.awt.Color(85, 65, 119));
        jButton24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton24.setForeground(new java.awt.Color(255, 255, 255));
        jButton24.setText("<< Back");
        jButton24.setToolTipText("");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jButton24)
                .addContainerGap(755, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        sellRequests.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, -1));

        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assests/In no time-amico.png"))); // NOI18N
        sellRequests.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 390, 330));

        add(sellRequests, "card12");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(myEquityHoldings.getSelectedRow()==-1)
        {
                JOptionPane.showMessageDialog(this, "Please select a share to sell");
                return;

        }
        this.selectedStock = this.business.getMarket().getStockMarket().getStockByName(String.valueOf(myEquityHoldings.getValueAt(myEquityHoldings.getSelectedRow(), 0)));
        txtShrName1.setText(selectedStock.getCompany().getName());
        changeScreen(jPanel6);
        jComboBox2.removeAllItems();
        jComboBox4.removeAllItems();
        for(String marketName:this.business.getMarket().getStockMarket().getMarketList()){
            jComboBox4.addItem(marketName);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        changeScreen(jPanel4);
        populateStockListTable();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if(tblStockListBuy.getSelectedRow()==-1)
        {
                JOptionPane.showMessageDialog(this, "Please select a share to buy");
                return;

        }
        String stockName = String.valueOf(tblStockListBuy.getValueAt(tblStockListBuy.getSelectedRow(), 0));
        this.selectedStock = this.business.getMarket().getStockMarket().getStockByName(stockName);
        jComboBox3.removeAll();
        changeScreen(jPanel3);
        System.out.println(this.business.getMarket().getStockMarket().getMarketList().size());
        for (String market : this.business.getMarket().getStockMarket().getMarketList()) {
            jComboBox3.addItem(market);
        }
        
        txtShrName.setText(this.selectedStock.getCompany().getName());
        setAvailableBalance(this.investmentManager.getAssignedCompany().getBalance());

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        changeScreen(jPanel1);
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnBuyShare1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyShare1ActionPerformed

            try{
        int qty = Integer.parseInt(String.valueOf(txtQtyShare.getText()));
        double price = qty * selectedStock.getPrice();
        if (price < this.investmentManager.getAssignedCompany().getCapital()) {
            this.investmentManager.getAssignedCompany().setBalance(this.investmentManager.getAssignedCompany().getBalance() - price);
            StockPurchaseRequest equityBuyRequest = new StockPurchaseRequest();
            equityBuyRequest.setBuyer(this.investmentManager.getAssignedCompany());
            equityBuyRequest.setStock(selectedStock);
            equityBuyRequest.setQuantity(Integer.parseInt(txtQtyShare.getText()));
            equityBuyRequest.setPurchaseID(this.business.getBrokerage().getPurchaseRequestCount());
            this.business.getBrokerage().setPurchaseRequestCount(this.business.getBrokerage().getPurchaseRequestCount() + 1);
            StockBroker equityBroker = this.business.getBrokerage().getStockBrokerByName(String.valueOf(jComboBox1.getSelectedItem()));
            equityBroker.getPurchaseRequests().add(equityBuyRequest);
            this.investmentManager.getAssignedCompany().getStockBuyRequests().add(equityBuyRequest);
            JOptionPane.showMessageDialog(this, "Buy Request Sent!");
            setAvailableBalance(this.investmentManager.getAssignedCompany().getBalance());
        } else {
            JOptionPane.showMessageDialog(this, "Not enough balance");
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Oops something went wrong");
        }
    }//GEN-LAST:event_btnBuyShare1ActionPerformed

    private void txtQtyShareInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtQtyShareInputMethodTextChanged

    }//GEN-LAST:event_txtQtyShareInputMethodTextChanged

    private void txtQtyShareKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyShareKeyPressed

    }//GEN-LAST:event_txtQtyShareKeyPressed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
       jComboBox3.removeAllItems();
       jComboBox1.removeAllItems();
       changeScreen(jPanel4);
    }//GEN-LAST:event_jButton11ActionPerformed

    private void btnSellShareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSellShareActionPerformed
        try{
            StockHoldings equityStockToSell = new StockHoldings();
            for (StockHoldings stockHoldings : this.investmentManager.getAssignedCompany().getStockHoldings()) {
                if (stockHoldings.getStock() == this.selectedStock) {
                    equityStockToSell = stockHoldings;
                }
            }
            if (Integer.parseInt(txtQtyShare1.getText()) <= equityStockToSell.getQuantity()) {
                StockSellRequest stockSellRequest = new StockSellRequest();
                stockSellRequest.setStock(selectedStock);
                stockSellRequest.setQuantity(Integer.parseInt(txtQtyShare1.getText()));
                stockSellRequest.setSeller(this.investmentManager.getAssignedCompany());
                stockSellRequest.setSaleID(this.business.getBrokerage().getSellRequestCount());
                this.business.getBrokerage().setSellRequestCount(this.business.getBrokerage().getSellRequestCount() + 1);
                StockBroker stockBroker = this.business.getBrokerage().getStockBrokerByName(String.valueOf(jComboBox2.getSelectedItem()));
                stockBroker.getSellRequests().add(stockSellRequest);
                this.investmentManager.getAssignedCompany().setBalance(this.investmentManager.getAssignedCompany().getBalance() + (Integer.parseInt(txtQtyShare1.getText()) * this.selectedStock.getPrice()));
                setAvailableBalance(this.investmentManager.getAssignedCompany().getBalance());
                this.investmentManager.getAssignedCompany().getStockSellRequests().add(stockSellRequest);
                JOptionPane.showMessageDialog(this, "Sell Request Sent!");
            } else {
                JOptionPane.showMessageDialog(this, "You do not have sufficient shares");
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Oops something went wrong!");
        }
    }//GEN-LAST:event_btnSellShareActionPerformed

    private void txtQtyShare1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtQtyShare1InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQtyShare1InputMethodTextChanged

    private void txtQtyShare1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyShare1KeyTyped

    }//GEN-LAST:event_txtQtyShare1KeyTyped

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        changeScreen(jPanel1);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            Company company = this.business.getCompliance().getComplianceModerator().getCompanyByName(String.valueOf(tblJobs.getValueAt(tblJobs.getSelectedRow(), 0)));
            jLabel18.setText(company.getName());
            jLabel18.setVisible(true);
            jLabel6.setVisible(true);
            jLabel3.setVisible(true);
            jLabel29.setVisible(true);
            txtSalary.setVisible(true);
            txtExperience.setVisible(true);
            jButton3.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Select an option");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtSalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSalaryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSalaryActionPerformed

    private void txtExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExperienceActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            Company company = this.business.getCompliance().getComplianceModerator().getCompanyByName(String.valueOf(tblJobs.getValueAt(tblJobs.getSelectedRow(), 0)));
            JobRequest jobRequest = new JobRequest();
            jobRequest.setCompany(company);
            jobRequest.setAppliedManager(this.investmentManager);
            jobRequest.setExperience(Integer.parseInt(txtExperience.getText()));
            jobRequest.setSalaryRequest(Double.parseDouble(txtSalary.getText()));
            Boolean uniqueRequest = true;
            for (JobRequest jobReq : company.getJobRequest()) {
                if (jobReq.getAppliedManager()== this.investmentManager) {
                    uniqueRequest = false;
                }
            }
            if (!uniqueRequest) {
                JOptionPane.showMessageDialog(this, "Cannot Apply For Same Company Twice!");
            } else {
                company.getJobRequest().add(jobRequest);
                JOptionPane.showMessageDialog(this, "Application Placed!");
            }
            
            business = DataContext.setBusiness(business);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Salary and experience should be numbers");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        changeScreen(jPanel1);
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        changeScreen(jPanel1);
    }//GEN-LAST:event_jButton24ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        changeScreen(buyRequests2);
        populateBuyRequestsTable();

    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        changeScreen(sellRequests);
        populateSellRequestsTable();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if(txtQtyShare.getText().isBlank())
        {
             JOptionPane.showMessageDialog(this, "Please enter a value");
             return;
        }
        try{    
        jLabel21.setText(String.valueOf(this.selectedStock.getPrice() * Integer.valueOf(txtQtyShare.getText())));
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(this, "Please enter a number"); 
           return;
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if(txtQtyShare1.getText().isBlank())
        {
             JOptionPane.showMessageDialog(this, "Please enter a value");
             return;
        }
        try{
            
        int a = Integer.valueOf(txtQtyShare1.getText());
        lblCLP1.setText(String.valueOf(this.selectedStock.getPrice() * a));
        }
        catch(Exception e)
        {
           JOptionPane.showMessageDialog(this, "Please enter a number");
           return;
        }
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
        jComboBox1.removeAllItems();
        for (StockBroker stockBroker : this.business.getBrokerage().getStockBrokers()) {
            String selectedMarket = String.valueOf(jComboBox3.getSelectedItem());
            if (stockBroker.getAssignedMarket().equals(selectedMarket)) {
                jComboBox1.addItem(stockBroker.getName());
            }
        }
        
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
       jComboBox2.removeAllItems();
        for (StockBroker stockBroker : this.business.getBrokerage().getStockBrokers()) {
            String selectedMarket = String.valueOf(jComboBox4.getSelectedItem());
            if (stockBroker.getAssignedMarket().equals(selectedMarket)) {
                jComboBox2.addItem(stockBroker.getName());
            }
        }
    }//GEN-LAST:event_jComboBox4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuyShare1;
    private javax.swing.JButton btnSellShare;
    private javax.swing.JPanel buyRequests2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel lblCLP1;
    private javax.swing.JTable myEquityHoldings;
    private javax.swing.JPanel sellRequests;
    private javax.swing.JTable tblJobs;
    private javax.swing.JTable tblStockListBuy;
    private javax.swing.JLabel txtAvailableBalance;
    private javax.swing.JLabel txtAvailableBalance1;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtQtyShare;
    private javax.swing.JTextField txtQtyShare1;
    private javax.swing.JTextField txtSalary;
    private javax.swing.JLabel txtShrName;
    private javax.swing.JLabel txtShrName1;
    // End of variables declaration//GEN-END:variables

    private void changeScreen(JPanel newJPanel) {
        this.removeAll();
        this.add(newJPanel);
        this.revalidate();
        this.repaint();
        jComboBox3.removeAll();
    }

    private void populateJobsTable() {
        DefaultTableModel model = (DefaultTableModel) tblJobs.getModel();
        model.setRowCount(0);
        for (Company company : this.business.getCompliance().getComplianceModerator().getCompanyList()) {
            if (company.getInvestmentManager() == null) {
                Object[] row = new Object[5];
                row[0] = company.getName();
                row[1] = company.getCapital();
                row[2] = company.getAssets();
                row[3] = company.getLiabilites();
                model.addRow(row);
            }
        }
    }

    private void populateHoldingsTable() {
        DefaultTableModel model = (DefaultTableModel) myEquityHoldings.getModel();
        model.setRowCount(0);
        double totalInvested = 0;
        double totalValuation = 0;
        for (StockHoldings stockHoldings : this.investmentManager.getAssignedCompany().getStockHoldings()) {
            Object[] row = new Object[6];
            row[0] = stockHoldings.getStock().getCompany().getName();
            row[1] = stockHoldings.getQuantity();
            row[2] = stockHoldings.getActualPrice();
            row[3] = stockHoldings.getStock().getPrice();
            totalInvested += stockHoldings.getQuantity() * stockHoldings.getActualPrice();
            row[4] = stockHoldings.getQuantity() * stockHoldings.getActualPrice();
            totalValuation += stockHoldings.getQuantity() * stockHoldings.getStock().getPrice();
            row[5] = stockHoldings.getQuantity() * stockHoldings.getStock().getPrice();
            model.addRow(row);
        }

    }
        
        
    private void populateStockListTable() {
        DefaultTableModel model = (DefaultTableModel) tblStockListBuy.getModel();
        model.setRowCount(0);
        for (Stock stock : this.business.getMarket().getStockMarket().getStockList()) {
            Object[] row = new Object[3];
            row[0] = stock.getCompany().getName();
            row[1] = stock.getPrice();
            row[2] = stock.getCompany().getCapital();
            model.addRow(row);
        }

    }

    private void setAvailableBalance(double balance) {
        txtAvailableBalance.setText(String.valueOf(balance));
        txtAvailableBalance1.setText(String.valueOf(balance));
    }

    private void populateBuyRequestsTable() {
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        model.setRowCount(0);
        for (StockPurchaseRequest stockBuyRequest : this.investmentManager.getAssignedCompany().getStockBuyRequests()) {
            Object[] row = new Object[4];
            row[0] = stockBuyRequest.getPurchaseID();
            row[1] = stockBuyRequest.getStock().getCompany().getName();
            row[2] = stockBuyRequest.getQuantity();
            row[3] = stockBuyRequest.getQuantity() * stockBuyRequest.getStock().getPrice();
            model.addRow(row);
        }
        
       
    }

    private void populateSellRequestsTable() {
         DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        model.setRowCount(0);
        for (StockSellRequest stockSellRequest : this.investmentManager.getAssignedCompany().getStockSellRequests()) {
            Object[] row = new Object[4];
            row[0] = stockSellRequest.getSaleID();
            row[1] = stockSellRequest.getStock().getCompany().getName();
            row[2] = stockSellRequest.getQuantity();
            row[3] = stockSellRequest.getQuantity() * stockSellRequest.getStock().getPrice();
            model.addRow(row);
        }
    }
}
